-- Keep the seeded database compatible with the current SQLAlchemy models.
ALTER TABLE IF EXISTS schoolers.website_settings
    ADD COLUMN IF NOT EXISTS icon_url VARCHAR(255);

ALTER TABLE IF EXISTS schoolers.schools
    ADD COLUMN IF NOT EXISTS logo_url VARCHAR(255);

ALTER TABLE IF EXISTS schoolers.staff
    ADD COLUMN IF NOT EXISTS email VARCHAR(120),
    ADD COLUMN IF NOT EXISTS present_address VARCHAR(255),
    ADD COLUMN IF NOT EXISTS permanent_address VARCHAR(255),
    ADD COLUMN IF NOT EXISTS aadhaar_card VARCHAR(30),
    ADD COLUMN IF NOT EXISTS emergency_number VARCHAR(30);

ALTER TABLE IF EXISTS schoolers.parents
    ADD COLUMN IF NOT EXISTS address VARCHAR(255),
    ADD COLUMN IF NOT EXISTS emergency_number VARCHAR(30);

ALTER TABLE IF EXISTS schoolers.teachers
    ADD COLUMN IF NOT EXISTS present_address VARCHAR(255),
    ADD COLUMN IF NOT EXISTS permanent_address VARCHAR(255),
    ADD COLUMN IF NOT EXISTS date_of_birth DATE,
    ADD COLUMN IF NOT EXISTS emergency_number VARCHAR(30),
    ADD COLUMN IF NOT EXISTS gender VARCHAR(20);

ALTER TABLE IF EXISTS schoolers.route_students
    ADD COLUMN IF NOT EXISTS status VARCHAR(10) NOT NULL DEFAULT 'pending';

CREATE TABLE IF NOT EXISTS schoolers.vehicles (
    vehicle_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id INTEGER NOT NULL REFERENCES schoolers.schools(school_id) ON DELETE CASCADE,
    vehicle_number VARCHAR(30) NOT NULL,
    vehicle_type VARCHAR(40),
    registration_number VARCHAR(40) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT vehicles_school_vehicle_number_key UNIQUE (school_id, vehicle_number)
);

CREATE TABLE IF NOT EXISTS schoolers.pilots (
    pilot_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL UNIQUE REFERENCES schoolers.users(user_id) ON DELETE CASCADE,
    school_id INTEGER NOT NULL REFERENCES schoolers.schools(school_id) ON DELETE CASCADE,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(120),
    phone VARCHAR(30) NOT NULL,
    present_address VARCHAR(255),
    permanent_address VARCHAR(255),
    aadhaar_number VARCHAR(30),
    dl_number VARCHAR(40),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
